/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.nimons360.data.remote.dto.response

import com.example.nimons360.data.remote.dto.request.*
import com.example.nimons360.data.remote.dto.response.*
import com.example.nimons360.data.remote.dto.common.*


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param iconUrl 
 * @param isMember 
 * @param familyCode 
 * @param createdAt 
 * @param updatedAt 
 * @param members 
 */


data class FamilyDetailResponse (

    @SerializedName("id")
    val id: kotlin.Int? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("iconUrl")
    val iconUrl: kotlin.String? = null,

    @SerializedName("isMember")
    val isMember: kotlin.Boolean? = null,

    @SerializedName("familyCode")
    val familyCode: kotlin.String? = null,

    @SerializedName("createdAt")
    val createdAt: kotlin.String? = null,

    @SerializedName("updatedAt")
    val updatedAt: kotlin.String? = null,

    @SerializedName("members")
    val members: kotlin.collections.List<FamilyDetailResponseMembersInner>? = null

)

