/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.nimons360.data.remote.dto.common

import com.example.nimons360.data.remote.dto.request.*
import com.example.nimons360.data.remote.dto.response.*
import com.example.nimons360.data.remote.dto.common.*


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param token 
 * @param expiresAt 
 * @param user 
 */


data class LoginData (

    @SerializedName("token")
    val token: kotlin.String? = null,

    @SerializedName("expiresAt")
    val expiresAt: kotlin.String? = null,

    @SerializedName("user")
    val user: UserData? = null

)

