/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.nimons360.data.remote.dto.common

import com.example.nimons360.data.remote.dto.request.*
import com.example.nimons360.data.remote.dto.response.*
import com.example.nimons360.data.remote.dto.common.*


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userId 
 * @param email 
 * @param fullName 
 * @param latitude 
 * @param longitude 
 * @param rotation 
 * @param batteryLevel 
 * @param isCharging 
 * @param internetStatus 
 * @param metadata 
 */


data class MemberPresenceUpdatedPayload (

    @SerializedName("userId")
    val userId: kotlin.Int? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("fullName")
    val fullName: kotlin.String? = null,

    @SerializedName("latitude")
    val latitude: kotlin.Double? = null,

    @SerializedName("longitude")
    val longitude: kotlin.Double? = null,

    @SerializedName("rotation")
    val rotation: kotlin.Double? = null,

    @SerializedName("batteryLevel")
    val batteryLevel: kotlin.Int? = null,

    @SerializedName("isCharging")
    val isCharging: kotlin.Boolean? = null,

    @SerializedName("internetStatus")
    val internetStatus: MemberPresenceUpdatedPayload.InternetStatus? = null,

    @SerializedName("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {

    /**
     * 
     *
     * Values: WIFI,MOBILE
     */
    enum class InternetStatus(val value: kotlin.String) {
        @SerializedName(value = "wifi") WIFI("wifi"),
        @SerializedName(value = "mobile") MOBILE("mobile");
    }
}

