/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.nimons360.data.remote.dto.common

import com.example.nimons360.data.remote.dto.request.*
import com.example.nimons360.data.remote.dto.response.*
import com.example.nimons360.data.remote.dto.common.*


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param payload 
 * @param timestamp 
 */


data class PingMessage (

    @SerializedName("type")
    val type: PingMessage.Type? = null,

    @SerializedName("payload")
    val payload: kotlin.Any? = null,

    @SerializedName("timestamp")
    val timestamp: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: PING
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "ping") PING("ping");
    }
}

