/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.nimons360.data.remote.dto.common

import com.example.nimons360.data.remote.dto.request.*
import com.example.nimons360.data.remote.dto.response.*
import com.example.nimons360.data.remote.dto.common.*


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param latitude 
 * @param longitude 
 * @param rotation Rotation in degrees (0-360)
 * @param batteryLevel Battery level percentage (0-100)
 * @param isCharging 
 * @param internetStatus 
 * @param metadata 
 */


data class UpdatePresencePayload (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("latitude")
    val latitude: kotlin.Double,

    @SerializedName("longitude")
    val longitude: kotlin.Double,

    /* Rotation in degrees (0-360) */
    @SerializedName("rotation")
    val rotation: kotlin.Double,

    /* Battery level percentage (0-100) */
    @SerializedName("batteryLevel")
    val batteryLevel: kotlin.Int,

    @SerializedName("isCharging")
    val isCharging: kotlin.Boolean,

    @SerializedName("internetStatus")
    val internetStatus: UpdatePresencePayload.InternetStatus,

    @SerializedName("metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {

    /**
     * 
     *
     * Values: WIFI,MOBILE
     */
    enum class InternetStatus(val value: kotlin.String) {
        @SerializedName(value = "wifi") WIFI("wifi"),
        @SerializedName(value = "mobile") MOBILE("mobile");
    }
}

