/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.nimons360.data.remote.dto.common

import com.example.nimons360.data.remote.dto.request.*
import com.example.nimons360.data.remote.dto.response.*
import com.example.nimons360.data.remote.dto.common.*


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param nim 
 * @param email 
 * @param fullName 
 * @param profileImageUrl 
 */


data class UserData (

    @SerializedName("id")
    val id: kotlin.Int? = null,

    @SerializedName("nim")
    val nim: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("fullName")
    val fullName: kotlin.String? = null,

    @SerializedName("profileImageUrl")
    val profileImageUrl: kotlin.String? = null

)

