/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.nimons360.data.remote.dto.request

import com.example.nimons360.data.remote.dto.request.*
import com.example.nimons360.data.remote.dto.response.*
import com.example.nimons360.data.remote.dto.common.*


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param familyId 
 * @param targetUserId 
 * @param message 
 */


data class SendGreetingRequest (

    @SerializedName("familyId")
    val familyId: kotlin.Int,

    @SerializedName("targetUserId")
    val targetUserId: kotlin.Int,

    @SerializedName("message")
    val message: kotlin.String

)

